import type { Listing, Category, Location } from './types';

export const LOCATIONS: Record<string, Record<string, string[]>> = {
  "Nigeria": {
    "Abia": ["Umuahia", "Aba"],
    "Adamawa": ["Yola", "Mubi"],
    "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene"],
    "Anambra": ["Awka", "Onitsha", "Nnewi"],
    "Bauchi": ["Bauchi", "Azare"],
    "Bayelsa": ["Yenagoa"],
    "Benue": ["Makurdi", "Gboko"],
    "Borno": ["Maiduguri", "Biu"],
    "Cross River": ["Calabar", "Ugep"],
    "Delta": ["Asaba", "Warri", "Sapele"],
    "Ebonyi": ["Abakaliki"],
    "Edo": ["Benin City", "Auchi"],
    "Ekiti": ["Ado-Ekiti", "Ikere-Ekiti"],
    "Enugu": ["Enugu", "Nsukka"],
    "Gombe": ["Gombe"],
    "Imo": ["Owerri", "Orlu"],
    "Jigawa": ["Dutse"],
    "Kaduna": ["Kaduna", "Zaria"],
    "Kano": ["Kano City", "Fagge", "Nassarawa"],
    "Katsina": ["Katsina", "Funtua"],
    "Kebbi": ["Birnin Kebbi"],
    "Kogi": ["Lokoja", "Okene"],
    "Kwara": ["Ilorin", "Offa"],
    "Lagos": ["Ikeja", "Lekki", "Victoria Island", "Surulere", "Ikorodu", "Badagry"],
    "Nasarawa": ["Lafia"],
    "Niger": ["Minna", "Suleja"],
    "Ogun": ["Abeokuta", "Ijebu-Ode", "Sango Otta"],
    "Ondo": ["Akure", "Ondo Town", "Owo"],
    "Osun": ["Osogbo", "Ile-Ife"],
    "Oyo": ["Ibadan", "Ogbomosho", "Oyo Town"],
    "Plateau": ["Jos", "Bukuru"],
    "Rivers": ["Port Harcourt", "Bonny Island", "Eleme", "Okrika"],
    "Sokoto": ["Sokoto"],
    "Taraba": ["Jalingo", "Wukari"],
    "Yobe": ["Damaturu"],
    "Zamfara": ["Gusau"],
    "Abuja (FCT)": ["Garki", "Wuse", "Maitama", "Asokoro", "Lugbe", "Kubwa"],
  },
  "Ghana": {
    "Greater Accra": ["Accra", "Tema", "Madina", "Legon"],
    "Ashanti": ["Kumasi", "Obuasi", "Ejisu"],
    "Western": ["Takoradi", "Sekondi", "Tarkwa"],
  },
  "Kenya": {
    "Nairobi": ["Westlands", "Karen", "CBD", "Kilimani"],
    "Mombasa": ["Mombasa Island", "Nyali", "Likoni"],
    "Kisumu": ["Kisumu City", "Milimani"],
  },
  "South Africa": {
    "Gauteng": ["Johannesburg", "Preoria", "Sandton", "Soweto"],
    "Western Cape": ["Cape Town", "Stellenbosch", "George"],
    "KwaZulu-Natal": ["Durban", "Pietermaritzburg", "Umhlanga"],
  }
};

export const CATEGORIES: Category[] = [
  {
    id: 'community',
    name: 'Community',
    subcategories: [
      { id: 'community-activities', name: 'Activities' },
      { id: 'community-artists', name: 'Artists' },
      { id: 'community-childcare', name: 'Childcare' },
      { id: 'community-classes', name: 'Classes' },
      { id: 'community-events', name: 'Events' },
      { id: 'community-pets', name: 'Pets' },
      { id: 'community-rideshare', name: 'Rideshare' },
      { id: 'community-volunteers', name: 'Volunteers' },
    ],
  },
  {
    id: 'housing',
    name: 'Housing',
    subcategories: [
      { id: 'housing-apartments', name: 'Apartments/Housing' },
      { id: 'housing-office', name: 'Office/Commercial' },
      { id: 'housing-rooms', name: 'Rooms/Shared' },
      { id: 'housing-sublets', name: 'Sublets/Temporary' },
      { id: 'housing-vacation', name: 'Vacation Rentals' },
    ],
  },
  {
    id: 'jobs',
    name: 'Jobs',
    subcategories: [
      { id: 'jobs-admin', name: 'Admin/Office' },
      { id: 'jobs-customer-service', name: 'Customer Service' },
      { id: 'jobs-labor', name: 'General Labor' },
      { id: 'jobs-marketing', name: 'Marketing' },
      { id: 'jobs-sales', name: 'Sales' },
      { id: 'jobs-software', name: 'Software/QA/DBA' },
      { id: 'jobs-writing-editing', name: 'Writing/Editing' },
    ],
  },
  {
    id: 'for-sale',
    name: 'For Sale',
    subcategories: [
      { id: 'for-sale-antiques', name: 'Antiques' },
      { id: 'for-sale-appliances', name: 'Appliances' },
      { id: 'for-sale-cars-trucks', name: 'Cars & Trucks' },
      { id: 'for-sale-electronics', name: 'Electronics' },
      { id: 'for-sale-fashion', name: 'Fashion' },
      { id: 'for-sale-furniture', name: 'Furniture' },
      { id: 'for-sale-home-garden', name: 'Home & Garden' },
      { id: 'for-sale-sporting', name: 'Sporting Goods' },
      { id: 'for-sale-toys-games', name: 'Toys & Games' },
    ],
  },
  {
    id: 'services',
    name: 'Services',
    subcategories: [
      { id: 'services-automotive', name: 'Automotive' },
      { id: 'services-beauty', name: 'Beauty' },
      { id: 'services-computer', name: 'Computer' },
      { id: 'services-creative', name: 'Creative' },
      { id: 'services-event', name: 'Event' },
      { id: 'services-financial', name: 'Financial' },
      { id: 'services-household', name: 'Household' },
      { id: 'services-legal', name: 'Legal' },
      { id: 'services-pet', name: 'Pet' },
    ],
  },
  {
    id: 'gigs',
    name: 'Gigs',
    subcategories: [
      { id: 'gigs-computer', name: 'Computer' },
      { id: 'gigs-creative', name: 'Creative' },
      { id: 'gigs-crew', name: 'Crew' },
      { id: 'gigs-domestic', name: 'Domestic' },
      { id: 'gigs-event', name: 'Event' },
      { id: 'gigs-labor', name: 'Labor' },
    ],
  },
];

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 1,
    title: 'Slightly Used iPhone 13 Pro',
    description: 'Excellent condition iPhone 13 Pro, 256GB, Sierra Blue. Comes with original box and charger. No scratches.',
    price: '₦350,000',
    category: 'for-sale-electronics',
    location: { country: 'Nigeria', state: 'Oyo', city: 'Ibadan' },
    imageUrl: 'https://picsum.photos/seed/iphone13/400/300',
    postDate: daysAgo(1),
    isFeatured: true,
    seller: {
      username: 'TechSavvyTunde',
      joinDate: 'Joined Jan 2022',
    },
  },
  {
    id: 2,
    title: '2015 Toyota Camry',
    description: 'Clean foreign used 2015 Toyota Camry. Automatic transmission, A/C chilling, engine in perfect condition.',
    price: 'GH₵ 85,000',
    category: 'for-sale-cars-trucks',
    location: { country: 'Ghana', state: 'Greater Accra', city: 'Accra' },
    imageUrl: 'https://picsum.photos/seed/camry2015/400/300',
    postDate: daysAgo(3),
    seller: {
      username: 'CarDealerKofi',
      joinDate: 'Joined Mar 2021',
    },
  },
  {
    id: 3,
    title: '3 Bedroom Apartment for Rent',
    description: 'Spacious 3 bedroom flat in a secure estate in Lekki. All rooms ensuite, with a modern kitchen.',
    price: '₦4,000,000/year',
    category: 'housing-apartments',
    location: { country: 'Nigeria', state: 'Lagos', city: 'Lekki' },
    imageUrl: 'https://picsum.photos/seed/apartment1/400/300',
    postDate: daysAgo(5),
    seller: {
      username: 'LagosProperties',
      joinDate: 'Joined May 2020',
    },
  },
  {
    id: 4,
    title: 'Graphic Designer Needed Urgently',
    description: 'A creative agency is looking for a skilled graphic designer with 3+ years of experience. Remote work available.',
    price: 'Competitive Salary',
    category: 'jobs-writing-editing',
    location: { country: 'Nigeria', state: 'Rivers', city: 'Port Harcourt' },
    imageUrl: 'https://picsum.photos/seed/designerjob/400/300',
    postDate: daysAgo(2),
    seller: {
      username: 'PHCreatives',
      joinDate: 'Joined Sep 2022',
    },
  },
  {
    id: 5,
    title: 'Handmade Ankara Dresses',
    description: 'Beautiful, custom-made Ankara dresses for all occasions. Available in various sizes and patterns.',
    price: 'KSh 4,500',
    category: 'for-sale-fashion',
    location: { country: 'Kenya', state: 'Nairobi', city: 'CBD' },
    imageUrl: 'https://picsum.photos/seed/ankara/400/300',
    postDate: daysAgo(7),
    isFeatured: true,
    seller: {
      username: 'AnkaraStyles',
      joinDate: 'Joined Feb 2023',
    },
  },
  {
    id: 6,
    title: 'L-Shaped Sofa Set',
    description: 'Comfortable and stylish 6-seater L-shaped sofa. Grey fabric, less than a year old.',
    price: 'R 7,000',
    category: 'for-sale-home-garden',
    location: { country: 'South Africa', state: 'Gauteng', city: 'Pretoria' },
    imageUrl: 'https://picsum.photos/seed/sofa/400/300',
    postDate: daysAgo(10),
    seller: {
      username: 'HomeDecorSA',
      joinDate: 'Joined Jul 2021',
    },
  },
  {
    id: 7,
    title: 'Professional Cleaning Services',
    description: 'We offer residential and commercial cleaning services. Deep cleaning, fumigation, and post-construction cleaning.',
    price: 'Request a Quote',
    category: 'services-household',
    location: { country: 'Nigeria', state: 'Abuja (FCT)', city: 'Wuse' },
    imageUrl: 'https://picsum.photos/seed/cleaning/400/300',
    postDate: now.toISOString(),
    seller: {
      username: 'AbujaCleaners',
      joinDate: 'Joined Nov 2020',
    },
  },
  {
    id: 8,
    title: 'Brand New PS5 Console',
    description: 'Playstation 5 Disc Edition, never opened. Comes with one controller. Serious buyers only.',
    price: 'R 12,000',
    category: 'for-sale-electronics',
    location: { country: 'South Africa', state: 'Western Cape', city: 'Cape Town' },
    imageUrl: 'https://picsum.photos/seed/ps5/400/300',
    postDate: daysAgo(4),
    isFeatured: true,
    seller: {
      username: 'GamerZA',
      joinDate: 'Joined Oct 2022',
    },
  }
];