import type { Listing, Category } from './types';

export const LOCATIONS: Record<string, Record<string, string[]>> = {
  "Nigeria": {
    "Lagos": ["Ikeja", "Lekki", "Victoria Island"],
    "Abuja": ["Garki", "Wuse", "Maitama"],
    "Rivers": ["Port Harcourt"],
  },
  "South Africa": {
    "Gauteng": ["Johannesburg", "Pretoria"],
    "Western Cape": ["Cape Town", "Stellenbosch"],
    "KwaZulu-Natal": ["Durban"],
  },
  "Kenya": {
    "Nairobi": ["Westlands", "Kilimani", "Karen"],
    "Mombasa": ["Mombasa Island", "Nyali"],
  },
  "Ghana": {
    "Greater Accra": ["Accra", "Tema"],
    "Ashanti": ["Kumasi"],
  },
  "Egypt": {
    "Cairo": ["New Cairo", "Zamalek", "Maadi"],
    "Alexandria": ["Alexandria"],
  },
  "Ethiopia": {
    "Addis Ababa": ["Bole", "Kirkos"],
  },
  "Tanzania": {
    "Dar es Salaam": ["Dar es Salaam"],
  },
  "Uganda": {
    "Central Region": ["Kampala"],
  }
};

export const CURRENCIES: Record<string, { symbol: string; name: string }> = {
  'NGN': { symbol: '₦', name: 'Nigerian Naira' },
  'ZAR': { symbol: 'R', name: 'South African Rand' },
  'KES': { symbol: 'KES', name: 'Kenyan Shilling' },
  'GHS': { symbol: 'GH₵', name: 'Ghanaian Cedi' },
  'EGP': { symbol: 'E£', name: 'Egyptian Pound' },
  'ETB': { symbol: 'Br', name: 'Ethiopian Birr' },
  'TZS': { symbol: 'TSh', name: 'Tanzanian Shilling' },
  'UGX': { symbol: 'USh', name: 'Ugandan Shilling' },
  'USD': { symbol: '$', name: 'US Dollar' },
};


export const CATEGORIES: Category[] = [
  {
    id: 'community',
    name: 'Community',
    subcategories: [
      { id: 'community-activities', name: 'Activities' },
      { id: 'community-artists', name: 'Artists' },
      { id: 'community-childcare', name: 'Childcare' },
      { id: 'community-classes', name: 'Classes' },
      { id: 'community-events', name: 'Events' },
      { id: 'community-pets', name: 'Pets' },
      { id: 'community-rideshare', name: 'Rideshare' },
      { id: 'community-volunteers', name: 'Volunteers' },
    ],
  },
  {
    id: 'housing',
    name: 'Housing',
    subcategories: [
      { id: 'housing-apartments', name: 'Apartments/Housing' },
      { id: 'housing-office', name: 'Office/Commercial' },
      { id: 'housing-rooms', name: 'Rooms/Shared' },
      { id: 'housing-sublets', name: 'Sublets/Temporary' },
      { id: 'housing-vacation', name: 'Vacation Rentals' },
    ],
  },
  {
    id: 'jobs',
    name: 'Jobs',
    subcategories: [
      { id: 'jobs-admin', name: 'Admin/Office' },
      { id: 'jobs-customer-service', name: 'Customer Service' },
      { id: 'jobs-labor', name: 'General Labor' },
      { id: 'jobs-marketing', name: 'Marketing' },
      { id: 'jobs-sales', name: 'Sales' },
      { id: 'jobs-software', name: 'Software/QA/DBA' },
      { id: 'jobs-writing-editing', name: 'Writing/Editing' },
    ],
  },
  {
    id: 'for-sale',
    name: 'For Sale',
    subcategories: [
      { id: 'for-sale-antiques', name: 'Antiques' },
      { id: 'for-sale-appliances', name: 'Appliances' },
      { id: 'for-sale-cars-trucks', name: 'Cars & Trucks' },
      { id: 'for-sale-electronics', name: 'Electronics' },
      { id: 'for-sale-fashion', name: 'Fashion' },
      { id: 'for-sale-furniture', name: 'Furniture' },
      { id: 'for-sale-home-garden', name: 'Home & Garden' },
      { id: 'for-sale-sporting', name: 'Sporting Goods' },
      { id: 'for-sale-toys-games', name: 'Toys & Games' },
    ],
  },
  {
    id: 'services',
    name: 'Services',
    subcategories: [
      { id: 'services-automotive', name: 'Automotive' },
      { id: 'services-beauty', name: 'Beauty' },
      { id: 'services-carpentry', name: 'Carpentry' },
      { id: 'services-computer', name: 'Computer' },
      { id: 'services-creative', name: 'Creative' },
      { id: 'services-domestic-help', name: 'Domestic Help' },
      { id: 'services-electrician', name: 'Electrician' },
      { id: 'services-event', name: 'Event' },
      { id: 'services-financial', name: 'Financial' },
      { id: 'services-handyman', name: 'Handyman' },
      { id: 'services-household', name: 'Household' },
      { id: 'services-labor', name: 'Labor (Skilled & Unskilled)' },
      { id: 'services-legal', name: 'Legal' },
      { id: 'services-movers', name: 'Movers & Packers' },
      { id: 'services-painting', name: 'Painting' },
      { id: 'services-pet', name: 'Pet' },
      { id: 'services-plumbing', name: 'Plumbing' },
    ],
  },
  {
    id: 'gigs',
    name: 'Gigs',
    subcategories: [
      { id: 'gigs-computer', name: 'Computer' },
      { id: 'gigs-creative', name: 'Creative' },
      { id: 'gigs-crew', name: 'Crew' },
      { id: 'gigs-domestic', name: 'Domestic' },
      { id: 'gigs-event', name: 'Event' },
      { id: 'gigs-labor', name: 'Labor' },
    ],
  },
];

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 1,
    title: 'Clean Tokunbo Toyota Corolla 2014',
    description: 'Foreign used Toyota Corolla 2014 model. Excellent condition, AC chilling, sound engine. Buy and drive. Nothing to fix.',
    price: '₦8,500,000',
    category: 'for-sale-cars-trucks',
    location: { country: 'Nigeria', state: 'Lagos', city: 'Ikeja' },
    imageUrl: 'https://picsum.photos/seed/corolla/400/300',
    postDate: daysAgo(1),
    isFeatured: true,
    seller: {
      username: 'LagosAutos',
      joinDate: 'Joined Jan 2022',
      rating: 4.8,
      reviewCount: 32,
    },
    deliveryMethods: ['in-person'],
    paymentMethods: ['bank-transfer'],
    acceptsEscrow: true,
    deliveryStatus: 'out-for-delivery',
  },
  {
    id: 9,
    title: 'Authentic Ankara Fabric - 6 Yards',
    description: 'High-quality, vibrant Ankara prints. Perfect for any occasion. Available in multiple designs. Price is for a full 6 yards.',
    price: 'GH₵350',
    category: 'for-sale-fashion',
    location: { country: 'Ghana', state: 'Greater Accra', city: 'Accra' },
    imageUrl: 'https://picsum.photos/seed/ankara/400/300',
    postDate: daysAgo(6),
    seller: {
      username: 'AccraFabrics',
      joinDate: 'Joined Apr 2023',
      rating: 4.9,
      reviewCount: 15,
    },
    deliveryMethods: ['courier', 'in-person'],
    paymentMethods: ['bank-transfer'],
    acceptsEscrow: false,
    deliveryStatus: 'shipped',
  },
    {
    id: 13,
    title: '3 Bedroom Apartment in Sandton',
    description: 'Spacious 3 bedroom apartment for rent in a secure complex in Sandton, Johannesburg. Modern finishes, pool, and 24/7 security.',
    price: 'R22,000/month',
    category: 'housing-apartments',
    location: { country: 'South Africa', state: 'Gauteng', city: 'Johannesburg' },
    imageUrl: 'https://picsum.photos/seed/sandtonapt/400/300',
    postDate: daysAgo(18),
    seller: {
      username: 'JoburgRealty',
      joinDate: 'Joined Feb 2021',
      rating: 4.5,
      reviewCount: 4,
    },
    deliveryMethods: ['in-person'],
    paymentMethods: ['bank-transfer'],
    acceptsEscrow: false,
  },
  {
    id: 3,
    title: 'Used Samsung Galaxy S21 Ultra',
    description: 'Neatly used Samsung S21 Ultra, 256GB. No cracks or major scratches. Working perfectly. Comes with charger and case.',
    price: 'KES 75,000',
    category: 'for-sale-electronics',
    location: { country: 'Kenya', state: 'Nairobi', city: 'Westlands' },
    imageUrl: 'https://picsum.photos/seed/samsungs21/400/300',
    postDate: daysAgo(5),
    seller: {
      username: 'NairobiGadgets',
      joinDate: 'Joined May 2020',
      rating: 5.0,
      reviewCount: 8,
    },
    deliveryMethods: ['courier', 'in-person'],
    paymentMethods: ['bank-transfer'],
    acceptsEscrow: true,
    deliveryStatus: 'delivered',
  },
  {
    id: 4,
    title: 'Senior Frontend Developer (React)',
    description: 'Hiring an experienced React developer for a leading fintech startup in Lagos. Must have 3+ years of experience. Remote work option available.',
    price: 'Competitive Salary',
    category: 'jobs-software',
    location: { country: 'Nigeria', state: 'Lagos', city: 'Lekki' },
    imageUrl: 'https://picsum.photos/seed/reactjobng/400/300',
    postDate: daysAgo(2),
    seller: {
      username: 'FintechNG',
      joinDate: 'Joined Sep 2022',
      rating: 4.7,
      reviewCount: 21,
    },
    deliveryMethods: ['email'],
    paymentMethods: ['bank-transfer'],
    acceptsEscrow: true,
  },
  {
    id: 10,
    title: 'Hand-carved Wooden Maasai Statues',
    description: 'Authentic, hand-carved Maasai couple statues. Made from ebony wood by local artisans. A beautiful piece of Kenyan culture for your home.',
    price: 'KES 8,000',
    category: 'for-sale-antiques',
    location: { country: 'Kenya', state: 'Nairobi', city: 'Karen' },
    imageUrl: 'https://picsum.photos/seed/maasai/400/300',
    postDate: daysAgo(12),
    isFeatured: true,
    seller: {
      username: 'KenyaCrafts',
      joinDate: 'Joined Aug 2021',
      rating: 5.0,
      reviewCount: 45,
    },
    deliveryMethods: ['courier'],
    paymentMethods: ['bank-transfer', 'other'],
    acceptsEscrow: true,
    deliveryStatus: 'processing',
  },
    {
    id: 14,
    title: 'Professional Event Planner & MC',
    description: 'Planning a wedding, birthday, or corporate event? I offer professional planning and MC services to make your event unforgettable. Based in Accra.',
    price: 'Request a Quote',
    category: 'services-event',
    location: { country: 'Ghana', state: 'Greater Accra', city: 'Accra' },
    imageUrl: 'https://picsum.photos/seed/eventplanner/400/300',
    postDate: daysAgo(25),
    isFeatured: true,
    seller: {
      username: 'EventsByAma',
      joinDate: 'Joined May 2019',
      rating: 4.9,
      reviewCount: 51,
    },
    deliveryMethods: ['in-person'],
    paymentMethods: ['bank-transfer', 'other'],
    acceptsEscrow: false,
  },
  {
    id: 2,
    title: 'Brand New Hisense 55" Smart TV',
    description: 'New Hisense 55-inch 4K UHD Smart TV with Dolby Vision. Still in the box. One year warranty included. Great for movies and gaming.',
    price: 'R8,500',
    category: 'for-sale-electronics',
    location: { country: 'South Africa', state: 'Western Cape', city: 'Cape Town' },
    imageUrl: 'https://picsum.photos/seed/hisensetv/400/300',
    postDate: daysAgo(3),
    seller: {
      username: 'CapeTownDeals',
      joinDate: 'Joined Mar 2021',
      rating: 4.2,
      reviewCount: 5,
    },
    deliveryMethods: ['in-person', 'courier'],
    paymentMethods: ['bank-transfer'],
    acceptsEscrow: true,
  },
  {
    id: 11,
    title: 'Office Space for Rent in Bole, Addis Ababa',
    description: 'Modern office space available in the heart of Bole. 150 sq meters with high-speed internet and backup generator. Ideal for startups and established businesses.',
    price: 'Br 80,000/month',
    category: 'housing-office',
    location: { country: 'Ethiopia', state: 'Addis Ababa', city: 'Bole' },
    imageUrl: 'https://picsum.photos/seed/addisoffice/400/300',
    postDate: daysAgo(8),
    seller: {
      username: 'AddisCommercial',
      joinDate: 'Joined Dec 2019',
      rating: 4.9,
      reviewCount: 67,
    },
    deliveryMethods: ['in-person'],
    paymentMethods: ['bank-transfer', 'other'],
    acceptsEscrow: false,
  },
  {
    id: 5,
    title: 'Aso-Ebi Lace Material for Weddings',
    description: 'High-quality sequence lace for traditional weddings and owambe parties. Available in various colours. Price per 5 yards.',
    price: '₦45,000',
    category: 'for-sale-fashion',
    location: { country: 'Nigeria', state: 'Lagos', city: 'Lagos Island' },
    imageUrl: 'https://picsum.photos/seed/asoebi/400/300',
    postDate: daysAgo(7),
    isFeatured: true,
    seller: {
      username: 'LagosFabrics',
      joinDate: 'Joined Feb 2023',
      rating: 4.8,
      reviewCount: 22,
    },
    deliveryMethods: ['courier', 'in-person'],
    paymentMethods: ['bank-transfer'],
    acceptsEscrow: true,
  },
    {
    id: 15,
    title: 'Graphic Designer for Hire',
    description: 'Freelance graphic designer available for logo design, branding, and social media graphics. Check out my portfolio. Quick turnaround.',
    price: 'Request a Quote',
    category: 'gigs-creative',
    location: { country: 'Nigeria', state: 'Lagos', city: 'Lekki' },
    imageUrl: 'https://picsum.photos/seed/designgig/400/300',
    postDate: daysAgo(11),
    seller: {
      username: 'CreativeNaija',
      joinDate: 'Joined Oct 2023',
      rating: 5.0,
      reviewCount: 3,
    },
    deliveryMethods: ['email'],
    paymentMethods: ['crypto', 'bank-transfer'],
    acceptsEscrow: true,
  },
];