import type { Category } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'community',
    name: 'Community',
    subcategories: [
      { id: 'community-activities', name: 'Activities' },
      { id: 'community-artists', name: 'Artists' },
      { id: 'community-childcare', name: 'Childcare' },
      { id: 'community-classes', name: 'Classes' },
      { id: 'community-events', name: 'Events' },
      { id: 'community-general', name: 'General' },
      { id: 'community-groups', name: 'Groups' },
      { id: 'community-local-news', name: 'Local News' },
      { id: 'community-lost-found', name: 'Lost & Found' },
      { id: 'community-musicians', name: 'Musicians' },
      { id: 'community-pets', name: 'Pets' },
      { id: 'community-politics', name: 'Politics' },
      { id: 'community-rideshare', name: 'Rideshare' },
      { id: 'community-volunteers', name: 'Volunteers' },
    ],
  },
  {
    id: 'services',
    name: 'Services',
    subcategories: [
      { id: 'services-automotive', name: 'Automotive' },
      { id: 'services-beauty', name: 'Beauty' },
      { id: 'services-cell-mobile', name: 'Cell & Mobile' },
      { id: 'services-computer', name: 'Computer' },
      { id: 'services-creative', name: 'Creative' },
      { id: 'services-event', name: 'Event' },
      { id: 'services-farm-garden', name: 'Farm & Garden' },
      { id: 'services-financial', name: 'Financial' },
      { id: 'services-household', name: 'Household' },
      { id: 'services-labor-move', name: 'Labor & Moving' },
      { id: 'services-legal', name: 'Legal' },
      { id: 'services-lessons', name: 'Lessons' },
      { id: 'services-pet', name: 'Pet' },
      { id: 'services-real-estate', name: 'Real Estate' },
      { id: 'services-skilled-trade', name: 'Skilled Trade' },
      { id: 'services-writing-editing', name: 'Writing & Editing' },
    ],
  },
  {
    id: 'housing',
    name: 'Housing',
    subcategories: [
      { id: 'housing-apartments', name: 'Apartments / Housing' },
      { id: 'housing-swap', name: 'Housing Swap' },
      { id: 'housing-wanted', name: 'Housing Wanted' },
      { id: 'housing-office', name: 'Office & Commercial' },
      { id: 'housing-parking-storage', name: 'Parking & Storage' },
      { id: 'housing-real-estate-for-sale', name: 'Real Estate for Sale' },
      { id: 'housing-rooms-shared', name: 'Rooms & Shared' },
      { id: 'housing-rooms-wanted', name: 'Rooms Wanted' },
      { id: 'housing-sublets-temporary', name: 'Sublets & Temporary' },
      { id: 'housing-vacation-rentals', name: 'Vacation Rentals' },
    ],
  },
  {
    id: 'for-sale',
    name: 'For Sale',
    subcategories: [
      { id: 'for-sale-antiques', name: 'Antiques' },
      { id: 'for-sale-appliances', name: 'Appliances' },
      { id: 'for-sale-arts-crafts', name: 'Arts & Crafts' },
      { id: 'for-sale-auto-parts', name: 'Auto Parts' },
      { id: 'for-sale-baby-kid', name: 'Baby & Kid' },
      { id: 'for-sale-barter', name: 'Barter' },
      { id: 'for-sale-bicycles', name: 'Bicycles' },
      { id: 'for-sale-boats', name: 'Boats' },
      { id: 'for-sale-books', name: 'Books' },
      { id: 'for-sale-business', name: 'Business' },
      { id: 'for-sale-cars-trucks', name: 'Cars & Trucks' },
      { id: 'for-sale-cds-dvds', name: 'CDs / DVDs' },
      { id: 'for-sale-cell-phones', name: 'Cell Phones' },
      { id: 'for-sale-clothing', name: 'Clothing & Accessories' },
      { id: 'for-sale-collectibles', name: 'Collectibles' },
      { id: 'for-sale-computers', name: 'Computers' },
      { id: 'for-sale-electronics', name: 'Electronics' },
      { id: 'for-sale-farm-garden', name: 'Farm & Garden' },
      { id: 'for-sale-free', name: 'Free Stuff' },
      { id: 'for-sale-furniture', name: 'Furniture' },
      { id: 'for-sale-garage-sale', name: 'Garage Sale' },
      { id: 'for-sale-general', name: 'General' },
      { id: 'for-sale-household', name: 'Household Items' },
      { id: 'for-sale-jewelry', name: 'Jewelry' },
      { id: 'for-sale-materials', name: 'Materials' },
      { id: 'for-sale-motorcycles', name: 'Motorcycles' },
      { id: 'for-sale-music-instruments', name: 'Music Instruments' },
      { id: 'for-sale-photo-video', name: 'Photo & Video' },
      { id: 'for-sale-sporting-goods', name: 'Sporting Goods' },
      { id: 'for-sale-tickets', name: 'Tickets' },
      { id: 'for-sale-tools', name: 'Tools' },
      { id: 'for-sale-toys-games', name: 'Toys & Games' },
      { id: 'for-sale-video-gaming', name: 'Video Gaming' },
    ],
  },
  {
    id: 'jobs',
    name: 'Jobs',
    subcategories: [
      { id: 'jobs-accounting-finance', name: 'Accounting & Finance' },
      { id: 'jobs-admin-office', name: 'Admin & Office' },
      { id: 'jobs-arch-engineering', name: 'Architecture & Engineering' },
      { id: 'jobs-art-media-design', name: 'Art, Media, & Design' },
      { id: 'jobs-biotech-science', name: 'Biotech & Science' },
      { id: 'jobs-business-mgmt', name: 'Business & Management' },
      { id: 'jobs-customer-service', name: 'Customer Service' },
      { id: 'jobs-education', name: 'Education' },
      { id: 'jobs-food-beverage', name: 'Food & Beverage' },
      { id: 'jobs-general-labor', name: 'General Labor' },
      { id: 'jobs-government', name: 'Government' },
      { id: 'jobs-human-resources', name: 'Human Resources' },
      { id: 'jobs-legal', name: 'Legal' },
      { id: 'jobs-manufacturing', name: 'Manufacturing' },
      { id: 'jobs-marketing', name: 'Marketing' },
      { id: 'jobs-medical-health', name: 'Medical & Health' },
      { id: 'jobs-nonprofit', name: 'Nonprofit Sector' },
      { id: 'jobs-real-estate', name: 'Real Estate' },
      { id: 'jobs-retail-wholesale', name: 'Retail & Wholesale' },
      { id: 'jobs-sales', name: 'Sales' },
      { id: 'jobs-salon-spa-fitness', name: 'Salon, Spa, & Fitness' },
      { id: 'jobs-security', name: 'Security' },
      { id: 'jobs-skilled-trade', name: 'Skilled Trade & Craft' },
      { id: 'jobs-software', name: 'Software & IT' },
      { id: 'jobs-transport', name: 'Transport' },
      { id: 'jobs-writing-editing', name: 'Writing & Editing' },
    ],
  },
  {
    id: 'gigs',
    name: 'Gigs',
    subcategories: [
      { id: 'gigs-computer', name: 'Computer' },
      { id: 'gigs-creative', name: 'Creative' },
      { id: 'gigs-crew', name: 'Crew' },
      { id: 'gigs-domestic', name: 'Domestic' },
      { id: 'gigs-event', name: 'Event' },
      { id: 'gigs-labor', name: 'Labor' },
      { id: 'gigs-talent', name: 'Talent' },
      { id: 'gigs-writing', name: 'Writing' },
    ],
  },
];

export const NIGERIAN_LOCATIONS = [
  { state: "Abia", lgas: ["Aba North", "Aba South", "Arochukwu", "Bende", "Ikwuano", "Isiala Ngwa North", "Isiala Ngwa South", "Isuikwuato", "Obi Ngwa", "Ohafia", "Osisioma", "Ugwunagbo", "Ukwa East", "Ukwa West", "Umuahia North", "Umuahia South", "Umu Nneochi"] },
  { state: "Adamawa", lgas: ["Demsa", "Fufure", "Ganye", "Gayuk", "Gombi", "Grie", "Hong", "Jada", "Larmurde", "Madagali", "Maiha", "Mayo-Belwa", "Michika", "Mubi North", "Mubi South", "Numan", "Shelleng", "Song", "Toungo", "Yola North", "Yola South"] },
  { state: "Akwa Ibom", lgas: ["Abak", "Eastern Obolo", "Eket", "Esit Eket", "Essien Udim", "Etim Ekpo", "Etinan", "Ibeno", "Ibesikpo Asutan", "Ibiono-Ibom", "Ika", "Ikono", "Ikot Abasi", "Ikot Ekpene", "Ini", "Itu", "Mbo", "Mkpat-Enin", "Nsit-Atai", "Nsit-Ibom", "Nsit-Ubium", "Obot Akara", "Okobo", "Onna", "Oron", "Oruk Anam", "Udung-Uko", "Ukanafun", "Uruan", "Urue-Offong/Oruko", "Uyo"] },
  { state: "Anambra", lgas: ["Aguata", "Anambra East", "Anambra West", "Anaocha", "Awka North", "Awka South", "Ayamelum", "Dunukofia", "Ekwusigo", "Idemili North", "Idemili South", "Ihiala", "Njikoka", "Nnewi North", "Nnewi South", "Ogbaru", "Onitsha North", "Onitsha South", "Orumba North", "Orumba South", "Oyi"] },
  { state: "Bauchi", lgas: ["Alkaleri", "Bauchi", "Bogoro", "Damban", "Darazo", "Dass", "Gamawa", "Ganjuwa", "Giade", "Itas/Gadau", "Jama'are", "Katagum", "Kirfi", "Misau", "Ningi", "Shira", "Tafawa Balewa", "Toro", "Warji", "Zaki"] },
  { state: "Bayelsa", lgas: ["Brass", "Ekeremor", "Kolokuma/Opokuma", "Nembe", "Ogbia", "Sagbama", "Southern Ijaw", "Yenagoa"] },
  { state: "Benue", lgas: ["Agatu", "Apa", "Ado", "Buruku", "Gboko", "Guma", "Gwer East", "Gwer West", "Katsina-Ala", "Konshisha", "Kwande", "Logo", "Makurdi", "Obi", "Ogbadibo", "Ohimini", "Oju", "Okpokwu", "Oturkpo", "Tarka", "Ukum", "Ushongo", "Vandeikya"] },
  { state: "Borno", lgas: ["Abadam", "Askira/Uba", "Bama", "Bayo", "Biu", "Chibok", "Damboa", "Dikwa", "Gubio", "Guzamala", "Gwoza", "Hawul", "Jere", "Kaga", "Kala/Balge", "Konduga", "Kukawa", "Kwaya Kusar", "Mafa", "Magumeri", "Maiduguri", "Marte", "Mobbar", "Monguno", "Ngala", "Nganzai", "Shani"] },
  { state: "Cross River", lgas: ["Abi", "Akamkpa", "Akpabuyo", "Bakassi", "Bekwarra", "Biase", "Boki", "Calabar Municipal", "Calabar South", "Etung", "Ikom", "Obanliku", "Obubra", "Obudu", "Odukpani", "Ogoja", "Yakuur", "Yala"] },
  { state: "Delta", lgas: ["Aniocha North", "Aniocha South", "Bomadi", "Burutu", "Ethiope East", "Ethiope West", "Ika North East", "Ika South", "Isoko North", "Isoko South", "Ndokwa East", "Ndokwa West", "Okpe", "Oshimili North", "Oshimili South", "Patani", "Sapele", "Udu", "Ughelli North", "Ughelli South", "Ukwuani", "Uvwie", "Warri North", "Warri South", "Warri South West"] },
  { state: "Ebonyi", lgas: ["Abakaliki", "Afikpo North", "Afikpo South (Edda)", "Ebonyi", "Ezza North", "Ezza South", "Ikwo", "Ishielu", "Ivo", "Izzi", "Ohaozara", "Ohaukwu", "Onicha"] },
  { state: "Edo", lgas: ["Akoko-Edo", "Egor", "Esan Central", "Esan North-East", "Esan South-East", "Esan West", "Etsako Central", "Etsako East", "Etsako West", "Igueben", "Ikpoba Okha", "Orhionmwon", "Oredo", "Ovia North-East", "Ovia South-West", "Owan East", "Owan West", "Uhunmwonde"] },
  { state: "Ekiti", lgas: ["Ado Ekiti", "Efon", "Ekiti East", "Ekiti South-West", "Ekiti West", "Emure", "Gbonyin", "Ido Osi", "Ijero", "Ikere", "Ikole", "Ilejemeje", "Irepodun/Ifelodun", "Ise/Orun", "Moba", "Oye"] },
  { state: "Enugu", lgas: ["Aninri", "Awgu", "Enugu East", "Enugu North", "Enugu South", "Ezeagu", "Igbo Etiti", "Igbo Eze North", "Igbo Eze South", "Isi Uzo", "Nkanu East", "Nkanu West", "Nsukka", "Oji River", "Udenu", "Udi", "Uzo Uwani"] },
  { state: "FCT", lgas: ["Abaji", "Bwari", "Gwagwalada", "Kuje", "Kwali", "Abuja Municipal Area Council"] },
  { state: "Gombe", lgas: ["Akko", "Balanga", "Billiri", "Dukku", "Funakaye", "Gombe", "Kaltungo", "Kwami", "Nafada", "Shongom", "Yamaltu/Deba"] },
  { state: "Imo", lgas: ["Aboh Mbaise", "Ahiazu Mbaise", "Ehime Mbano", "Ezinihitte", "Ideato North", "Ideato South", "Ihitte/Uboma", "Ikeduru", "Isiala Mbano", "Isu", "Mbaitoli", "Ngor Okpala", "Njaba", "Nkwerre", "Nwangele", "Obowo", "Oguta", "Ohaji/Egbema", "Okigwe", "Orlu", "Orsu", "Oru East", "Oru West", "Owerri Municipal", "Owerri North", "Owerri West", "Unuimo"] },
  { state: "Jigawa", lgas: ["Auyo", "Babura", "Biriniwa", "Birnin Kudu", "Buji", "Dutse", "Gagarawa", "Garki", "Gumel", "Guri", "Gwaram", "Gwiwa", "Hadejia", "Jahun", "Kafin Hausa", "Kaugama", "Kazaure", "Kiri Kasama", "Kiyawa", "Kaugama", "Maigatari", "Malam Madori", "Miga", "Ringim", "Roni", "Sule Tankarkar", "Taura", "Yankwashi"] },
  { state: "Kaduna", lgas: ["Birnin Gwari", "Chikun", "Giwa", "Igabi", "Ikara", "Jaba", "Jema'a", "Kachia", "Kaduna North", "Kaduna South", "Kagarko", "Kajuru", "Kaura", "Kauru", "Kubau", "Kudan", "Lere", "Makarfi", "Sabon Gari", "Sanga", "Soba", "Zangon Kataf", "Zaria"] },
  { state: "Kano", lgas: ["Ajingi", "Albasu", "Bagwai", "Bebeji", "Bichi", "Bunkure", "Dala", "Dambatta", "Dawakin Kudu", "Dawakin Tofa", "Doguwa", "Fagge", "Gabasawa", "Garko", "Garun Mallam", "Gaya", "Gezawa", "Gwale", "Gwarzo", "Kabo", "Kano Municipal", "Karaye", "Kibiya", "Kiru", "Kumbotso", "Kunchi", "Kura", "Madobi", "Makoda", "Minjibir", "Nasarawa", "Rano", "Rimin Gado", "Rogo", "Shanono", "Sumaila", "Takai", "Tarauni", "Tofa", "Tsanyawa", "Tudun Wada", "Ungogo", "Warawa", "Wudil"] },
  { state: "Katsina", lgas: ["Bakori", "Batagarawa", "Batsari", "Baure", "Bindawa", "Charanchi", "Dandume", "Danja", "Dan Musa", "Daura", "Dutsi", "Dutsin Ma", "Faskari", "Funtua", "Ingawa", "Jibia", "Kafur", "Kaita", "Kankara", "Kankia", "Katsina", "Kurfi", "Kusada", "Mai'Adua", "Malumfashi", "Mani", "Mashi", "Matazu", "Musawa", "Rimi", "Sabuwa", "Safana", "Sandamu", "Zango"] },
  { state: "Kebbi", lgas: ["Aleiro", "Arewa Dandi", "Argungu", "Augie", "Bagudo", "Birnin Kebbi", "Bunza", "Dandi", "Fakai", "Gwandu", "Jega", "Kalgo", "Koko/Besse", "Maiyama", "Ngaski", "Sakaba", "Shanga", "Suru", "Wasagu/Danko", "Yauri", "Zuru"] },
  { state: "Kogi", lgas: ["Adavi", "Ajaokuta", "Ankpa", "Bassa", "Dekina", "Ibaji", "Idah", "Igalamela Odolu", "Ijumu", "Kabba/Bunu", "Kogi", "Lokoja", "Mopa Muro", "Ofu", "Ogori/Magongo", "Okehi", "Okene", "Olamaboro", "Omala", "Yagba East", "Yagba West"] },
  { state: "Kwara", lgas: ["Asa", "Baruten", "Edu", "Ekiti", "Ifelodun", "Ilorin East", "Ilorin South", "Ilorin West", "Irepodun", "Isin", "Kaiama", "Moro", "Offa", "Oke Ero", "Oyun", "Pategi"] },
  { state: "Lagos", lgas: ["Agege", "Ajeromi-Ifelodun", "Alimosho", "Amuwo-Odofin", "Apapa", "Badagry", "Epe", "Eti Osa", "Ibeju-Lekki", "Ifako-Ijaiye", "Ikeja", "Ikorodu", "Kosofe", "Lagos Island", "Lagos Mainland", "Mushin", "Ojo", "Oshodi-Isolo", "Shomolu", "Surulere"] },
  { state: "Nasarawa", lgas: ["Akwanga", "Awe", "Doma", "Karu", "Keana", "Keffi", "Lafia", "Nasarawa", "Nasarawa Egon", "Obi", "Toto", "Wamba"] },
  { state: "Niger", lgas: ["Agaie", "Agwara", "Bida", "Borgu", "Bosso", "Chanchaga", "Edati", "Gbako", "Gurara", "Katcha", "Kontagora", "Lapai", "Lavun", "Magama", "Mariga", "Mashegu", "Mokwa", "Moya", "Paikoro", "Rafi", "Rijau", "Shiroro", "Suleja", "Tafa", "Wushishi"] },
  { state: "Ogun", lgas: ["Abeokuta North", "Abeokuta South", "Ado-Odo/Ota", "Egbado North", "Egbado South", "Ewekoro", "Ifo", "Ijebu East", "Ijebu North", "Ijebu North East", "Ijebu Ode", "Ikenne", "Imeko Afon", "Ipokia", "Obafemi Owode", "Odeda", "Odogbolu", "Ogun Waterside", "Remo North", "Shagamu"] },
  { state: "Ondo", lgas: ["Akoko North-East", "Akoko North-West", "Akoko South-West", "Akoko South-East", "Akure North", "Akure South", "Ese Odo", "Idanre", "Ifedore", "Ilaje", "Ile Oluji/Okeigbo", "Irele", "Odigbo", "Okitipupa", "Ondo East", "Ondo West", "Ose", "Owo"] },
  { state: "Osun", lgas: ["Atakunmosa East", "Atakunmosa West", "Aiyedaade", "Aiyedire", "Boluwaduro", "Boripe", "Ede North", "Ede South", "Ife Central", "Ife East", "Ife North", "Ife South", "Egbedore", "Ejigbo", "Ifedayo", "Ifelodun", "Ila", "Ilesa East", "Ilesa West", "Irepodun", "Irewole", "Isokan", "Iwo", "Obokun", "Odo Otin", "Ola Oluwa", "Olorunda", "Oriade", "Orolu", "Osogbo"] },
  { state: "Oyo", lgas: ["Afijio", "Akinyele", "Atiba", "Atisbo", "Egbeda", "Ibadan North", "Ibadan North-East", "Ibadan North-West", "Ibadan South-East", "Ibadan South-West", "Ibarapa Central", "Ibarapa East", "Ibarapa North", "Ido", "Irepo", "Iseyin", "Itesiwaju", "Iwajowa", "Kajola", "Lagelu", "Ogbomosho North", "Ogbomosho South", "Ogo Oluwa", "Olorunsogo", "Oluyole", "Ona Ara", "Orelope", "Ori Ire", "Oyo", "Oyo East", "Saki East", "Saki West", "Surulere"] },
  { state: "Plateau", lgas: ["Bokkos", "Barkin Ladi", "Bassa", "Jos East", "Jos North", "Jos South", "Kanam", "Kanke", "Langtang South", "Langtang North", "Mangu", "Mikang", "Pankshin", "Qua'an Pan", "Riyom", "Shendam", "Wase"] },
  { state: "Rivers", lgas: ["Port Harcourt", "Obio-Akpor", "Okrika", "Ogu–Bolo", "Eleme", "Tai", "Gokana", "Khana", "Oyigbo", "Opobo–Nkoro", "Andoni", "Bonny", "Degema", "Asari-Toru", "Akuku-Toru", "Abua–Odual", "Ahoada West", "Ahoada East", "Ogba–Egbema–Ndoni", "Emuoha", "Ikwerre", "Etche", "Omuma"] },
  { state: "Sokoto", lgas: ["Binji", "Bodinga", "Dange Shuni", "Gada", "Goronyo", "Gudu", "Gwadabawa", "Illela", "Isa", "Kebbe", "Kware", "Rabah", "Sabon Birni", "Shagari", "Silame", "Sokoto North", "Sokoto South", "Tambuwal", "Tangaza", "Tureta", "Wamako", "Wurno", "Yabo"] },
  { state: "Taraba", lgas: ["Ardo Kola", "Bali", "Donga", "Gashaka", "Gassol", "Ibi", "Jalingo", "Karim Lamido", "Kumi", "Lau", "Sardauna", "Takum", "Ussa", "Wukari", "Yorro", "Zing"] },
  { state: "Yobe", lgas: ["Bade", "Bursari", "Damaturu", "Fika", "Fune", "Geidam", "Gujba", "Gulani", "Jakusko", "Karasuwa", "Machina", "Nangere", "Nguru", "Potiskum", "Tarmuwa", "Yunusari", "Yusufari"] },
  { state: "Zamfara", lgas: ["Anka", "Bakura", "Birnin Magaji/Kiyaw", "Bukkuyum", "Bungudu", "Gummi", "Gusau", "Kaura Namoda", "Maradun", "Maru", "Shinkafi", "Talata Mafara", "Chafe", "Zurmi"] }
];